# Generated by Django 4.1.7 on 2024-04-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images'),
        ),
    ]
